version: '3.7'
 
services:
  mysql:
    image: mysql
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: stock_data
      MYSQL_USER: bend
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Add the user creation script
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql  # Add a volume to persist MySQL data
    networks:
      - my-network
    ports:
      - "3306:3306"
    restart: always
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Explicitly mention Dockerfile name if not default
    container_name: backend-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=my-mysql-container
      - DB_USER=bend
      - DB_PASSWORD=123456789
      - DB_DATABASE=stock_data
    networks:
      - my-network
    ports:
      - "5050:5050"
    restart: always
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Explicitly mention Dockerfile name if not default
    container_name: frontend-container
    depends_on:
      - backend
    networks:
      - my-network
    ports:
      - "3000:3000"
    restart: always
 
networks:
  my-network:
    driver: bridge
 
volumes:
  mysql_data:
    driver: local